### ISSUE TITLE
 Invalid header: Does not start with Cr24

### ISSUE THREAD

**Issue by vijayjai12** [MarshallOfSound/electron-devtools-installer#249] opened 2024-12-13 09:48 UTC
I am unable to use the devtools. After building my application I receive the following in my CLI:
[2] 14:38:27.954 › An error occurred while installing dev tools:  Error: Invalid header: Does not start with Cr24
[2]     at crxToZip (/home/desktop-app/node_modules/unzip-crx-3/dist/index.js:32:15)
[2]     at /home/desktop-app/node_modules/unzip-crx-3/dist/index.js:69:32
[2]     at callHanler (/home/desktop-app/node_modules/yaku/lib/yaku.js:719:16)
[2]     at tryCatcher (/home/desktop-app/node_modules/yaku/lib/yaku.js:436:32)
[2]     at /home/desktop-app/node_modules/yaku/lib/yaku.js:575:38
[2]     at flush (/home/desktop-app/node_modules/yaku/lib/yaku.js:478:17)
[2]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

After much research, it appears this error has to do with how the library downloads the extension from google?

I tried inserting the chrome extension id explicitly like so:

await installExtension("nhdogjmejiglipccpnnnanhbledajbpd"); 
but I still receive the same error

**Comment by iamMikeLe** [comment] 2024-12-13 12:05
I have the same issue, it was working without issue yesterday and it started today

**Comment by diegorom6** [comment] 2024-12-13 15:36
Same issue here, stopping me from doing my job.

**Comment by timthedevguy** [comment] 2024-12-13 19:12
I had same issue, I just followed the Manual Instructions at https://www.electronjs.org/docs/latest/tutorial/devtools-extension#manually-loading-a-devtools-extension and it works just fine

**Comment by sebbean** [comment] 2024-12-14 06:58
me too gang!

maybe chrome's url structure is broken?

**Comment by sebbean** [comment] 2024-12-14 06:58
yea - seems like the url is no longer valid that it tries to download

`https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&x=id%3Dlmhkpmbekcpmknklioeibfkpmmfibljd%26uc&prodversion=32`

**Comment by RichardKanshen** [comment] 2024-12-15 15:12
I messed around with the downloads from the extension store, and the most minimal URL that seems to be working as intended is this: `https://clients2.google.com/service/update2/crx?response=redirect&prodversion=131.0.6778.86&&acceptformat=crx2,crx3&x=id%3Dlmhkpmbekcpmknklioeibfkpmmfibljd%26uc`
Notably, the `prodversion` param is very different. Same thing goes for React Dev Tools, and presumably all other extensions.
After a little digging, this is a version of the chromium engine, and can be found in the node_module electron-to-chromium, and its file full-chromium-versions.js.
This file exports an object with keys - chromium version - corresponding to arrays of strings - electron versions.
it looks something like this:
module.exports = {
    ...
    "126.0.6478.183": [
		"31.3.0"
	],
	...
}
So, the fix, how I see it, is find the version of electron, get the key to the array containing it, and use the `prodversion` with the value of the key. For ex. Electron version 31.3.0 would use the `prodVersion` 126.0.6478.183

**Comment by RichardKanshen** [comment] 2024-12-15 16:19
I have tried messing around a lot, and eventually got *somewhere* close to it working.
I removed old extensions which do not exist anymore, and also some EXTREMELY OLD things that were holding this back from further updates (mostly just things that were deprecated with the release of Electron 13.0.0)
I have pushed everything I did on GitHub, any feedback / help appreciated.
https://github.com/RichardKanshen/electron-devtools-installer

**Comment by RichardKanshen** [comment] 2024-12-15 16:26
updated the deps in a test project, and react devtools work now. yay!
![image](https://github.com/user-attachments/assets/7fb88a49-c9a3-4950-a2dc-00182b37e32f)

**Comment by RichardKanshen** [comment] 2024-12-15 16:43
Filed a PR @ #250, but doubt it will get merged, since the tests are supposed to work for archaic versions of electron, and the node version in the tests are outdated.

**Comment by menushka** [comment] 2024-12-16 00:10
Ran into the same issue, running it with `allowFileAccess` fixed it for me
```js
await installExtension([REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS], {
  loadExtensionOptions: {
    allowFileAccess: true,
  },
});
```

**Comment by erickzhao** [comment] 2024-12-16 18:50
The `prodversion` param should be the only thing you need to change here. If you try to access the URLs in your web page, you'll see that having `prodversion=32` will noop while changing it to a more modern Chrome version (e.g. 130) will access the extension properly.

```diff
diff --git a/node_modules/electron-devtools-installer/dist/downloadChromeExtension.js b/node_modules/electron-devtools-installer/dist/downloadChromeExtension.js
index 4a0ef2a..ef97420 100644
--- a/node_modules/electron-devtools-installer/dist/downloadChromeExtension.js
+++ b/node_modules/electron-devtools-installer/dist/downloadChromeExtension.js
@@ -16,7 +16,7 @@ const downloadChromeExtension = (chromeStoreID, forceDownload, attempts = 5) =>
             if (fs.existsSync(extensionFolder)) {
                 rimraf.sync(extensionFolder);
             }
-            const fileURL = `https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&x=id%3D${chromeStoreID}%26uc&prodversion=32`; // eslint-disable-line
+            const fileURL = `https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&x=id%3D${chromeStoreID}%26uc&prodversion=130.0.6723.137`; // eslint-disable-line
             const filePath = path.resolve(`${extensionFolder}.crx`);
             utils_1.downloadFile(fileURL, filePath)
                 .then(() => {
```

**Comment by RichardKanshen** [comment] 2024-12-17 06:19
> The `prodversion` param should be the only thing you need to change here.

yup! that is the issue here.

**Comment by RichardKanshen** [comment] 2024-12-17 06:30
@vijayjai12 could you reopen this issue? This is still an issue in the package that should probably be fixed up.

**Closed** 2024-12-17 20:35 UTC
