### ISSUE TITLE
Electron v9.0.0

### ISSUE THREAD

**Issue by sirtimid** [MarshallOfSound/electron-devtools-installer#130] opened 2020-05-19 09:28 UTC
Is there any plan to migrate to the new stable version of Electron?

`BrowserWindow.getDevToolsExtensions` and `BrowserWindow.addDevToolsExtension` are deprecated and will be removed.

**Comment by develerik** [comment] 2020-05-24 21:02
I already opened a pull request to fix this (#131)

**Comment by DmitryMK** [comment] 2020-06-03 06:40
There seems to be a different issue with Electron 9.x at the moment, which does not allow to use extensions, when loading your app using file:// or browserWindow.loadFile. It is not related to this repository, but it might help those who are facing the issue that devtools does not work in 9.x.

**Comment by develerik** [comment] 2020-06-03 06:45
I'm using the vue devtools in my electron 9 project and they are working fine. In development I use 'browserWindow.loadUrl("file://...")`

**Comment by proto6** [comment] 2020-06-17 06:25
I can confirm that redux dev tools do NOT work in Electron 9.0.4 but do work in 8.3.1

**Comment by khanh-bes** [comment] 2020-07-01 06:51
react dev tools is not working either

**Comment by tom-james-watson** [comment] 2020-07-15 09:40
With https://github.com/MarshallOfSound/electron-devtools-installer/pull/131 now being merged, this now looks like it's an upstream issue with electron and/or the extensions themselves - https://github.com/electron/electron/issues/23662

**Comment by petef19** [comment] 2020-07-19 01:46
still not working on Electron 9.1.0 - I opened ticket [here](https://github.com/electron/electron/issues/24638)

**Comment by Keimeno** [comment] 2021-11-17 09:49
It works on electron v9+ if you install the extensions after the `app.on "ready"` event, and when passing the following `installExtension` options `{ loadExtensionOptions: { allowFileAccess: true } }`

**Comment by MarshallOfSound** [comment] 2024-12-17 22:20
Electron 9.0.0 is supported 👍

**Closed by MarshallOfSound** 2024-12-17 22:20 UTC
